l1 = ('apple', 'pineapple', 'banana')
l2 = ('japan', 'egypt', 'spain')
l3 = l1 + l2
print('l1:', l1)
print('l2:', l2)
print('l3:', l3)
print('l1[1]:', l1[1])
print('l1[-1]:', l1[-1])
print('l3[2:-1]', l3[2:-1])
print('l3:')
for x in l3:
  print('  -', x)
print('japan in l1:', 'japan' in l1)
print('japan in l3:', 'japan' in l3)
print('len(l3):', len(l3))
